### ISSUE TITLE
Not an issue but a question.

### ISSUE THREAD

**Issue by twistedcinema** [ElNelyo/esx_discord_bot#5]
Am I able to go about adding something that will notify me if people use a .lua injector to spawn money? I'm having a big issue with this and its a hassle to monitor the database all day when I have stuff going on.

**Comment by HumanTree92** [comment]
@twistedcinema I have implemented a Player time tracker. And i check it every now & then. Pretty much if a player has a lot of cars & money in a short period of time i give them an auto Perm Ban. AFAIK rn there ain't a way to notify on a lua injector. However tho i would try out https://forum.fivem.net/t/release-dev-server-event-security-tokens-anticheat/139189 and see if this works out for ya.
